spring:
  datasource:
    username: root
    password: root123456
    url: jdbc:mysql://47.106.197.28:3306/demo?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088

#client:
#  config:
#    URL: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
#    USERNAME: root
#    PASSWORD: 123456
#    DRIVER: com.mysql.cj.jdbc.Driver