spring:
  datasource:
    username: zjm
    password: 2Zhl1Hbl
    url: jdbc:mysql://rm-wz9u2f2r8un3057j0to.mysql.rds.aliyuncs.com:3306/smartlims?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8082

client:
  config:
    URL: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    USERNAME: root
    PASSWORD: 123456
    DRIVER: com.mysql.cj.jdbc.Driver